### ISSUE TITLE
bug on aac.c

### ISSUE THREAD

**Issue by libTorrentUser** [bookkojot/mp4fixer#11]
There is a bug on aac.c, line 187

`NeAACDecHandle h=NeAACDecOpen();`

in order to fix it, just chang it to 

`h=NeAACDecOpen();`

it is the reason a lot of people is complaining about crashes, seg-fault, etc. Quite silly once you find it. I bet someone ctrl+c, ctrl+v that part of the code, isn't that right, bookkojot? 
:)

**Comment by bookkojot** [comment]
Maybe, it was soo loooon agooooo...
Thanks, for fix!

**Comment by libTorrentUser** [comment]
I should be the one thanking you. I was trying to recover a broken mp4 file, and although I was able to recover the video (doing pretty much the same thing you did), I was having no luck with the audio. Then I saw your code and tried your idea of converting *AAC* audio from the "working" file to *adts* and use its header on the audio data extracted from the broken file + *faad* to generate a fixed *ACC* stream in *adts*.

So, thank YOU :)
