### ISSUE TITLE
Unable to play h64 video

### ISSUE THREAD

**Issue by Algebro7** [bookkojot/mp4fixer#7]
Hello,
I've just tried this project after realizing that `untrunc` cannot recover files bigger than ~4GB, and I'm having issues recovering this mp4. I ran the tool and after a lot of messages like `Got! 65638 bytes and 362 shit`, I saw the following output:
```
  File: testing-out-video.h264
  Size: 10664699948	Blocks: 20829504   IO Block: 4096   regular file
Device: fe04h/65028d	Inode: 55325937    Links: 1
```
I then attempted to play the video with ffplay and just saw an endless stream of the following errors:
```
[NULL @ 0x7f0b8c002900] non-existing PPS 0 referenced
    Last message repeated 4 times
[h264 @ 0x7f0b8c1ecd40] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c1ecd40] decode_slice_header error
[h264 @ 0x7f0b8c1ecd40] no frame!
[NULL @ 0x7f0b8c002900] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c209040] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c209040] decode_slice_header error
[h264 @ 0x7f0b8c209040] no frame!
[NULL @ 0x7f0b8c002900] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c005600] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c005600] decode_slice_header error
[h264 @ 0x7f0b8c005600] no frame!
[NULL @ 0x7f0b8c002900] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x7f0b8c01b280] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c01b280] decode_slice_header error
[h264 @ 0x7f0b8c01b280] no frame!
[NULL @ 0x7f0b8c002900] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c0a3e40] non-existing PPS 0 referenced
[h264 @ 0x7f0b8c0a3e40] decode_slice_header error
[h264 @ 0x7f0b8c0a3e40] no frame!
[NULL @ 0x7f0b8c002900] non-existing PPS 0 referenced
```
I also ran aacfixer to try and recover the sound and got about 30 seconds worth of audio back, but the tool segfaulted. Let me know if I can provide any other information that would be helpful to debug. I'm afraid I can't upload a sample of the broken file because its quite large (~14GB).

Thanks!

**Comment by bookkojot** [comment]
Hi! You still need help?

**Comment by Algebro7** [comment]
Nope, @anthwlock was able to update his fork of [untrunc](https://github.com/anthwlock/untrunc/) to support large files and it was able to recover the video. Thanks!
